services:
  db:
    image: ghcr.io/library/postgres:16
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: unless-stopped

  mattermost:
    image: ghcr.io/mattermost/mattermost-team-edition:latest
    depends_on:
      - db
    ports:
      - "8065:8065"
    environment:
      - MM_SQLSETTINGS_DRIVERNAME=postgres
      - MM_SQLSETTINGS_DATASOURCE=postgres://mmuser:mmuser_password@db:5432/mattermost?sslmode=disable&connect_timeout=10
      - MM_SERVICESETTINGS_SITEURL=http://localhost:8065
    volumes:
      - ./data/mattermost:/mattermost/data
    restart: unless-stopped
